### ISSUE TITLE
Preset buttons change the LED display however speed doesn't get applied. 

### ISSUE THREAD

**Issue by Therrixxe** [scrapcomputing/ThrottleBlaster#13]
When the preset button is pressed the display is changed however the new speed doesn't take effect.

**Comment by scrapcomputing** [comment]
Oops! I have updated the rev 0.7 firmware file in the releases. Please try that one.
Thanks!

**Comment by Therrixxe** [comment]
It applies the settings now however it appear to jump to the value 4 8 10 25 33 66 133 etc not the modified preset.

**Comment by scrapcomputing** [comment]
Thanks once again for spotting the bug. It should be fixed now. Please try the latest rev 0.7 firmware file. Thanks!

**Comment by Therrixxe** [comment]
That fixed it. Working great now thanks again!
