### ISSUE TITLE
MAX3232 or MAX232?

### ISSUE THREAD

**Issue by oXL0C0Xo** [scrapcomputing/ThrottleBlaster#16]
I know that the project calls for a MAX3232 which I did order, but the package size seems almost too small. I do have some MAX232 in stock, do you think these will be a compatible substitute? I might just try it to see if it works, was just wondering if you have before I spend a bunch of time soldering this up.

Thanks!

**Comment by scrapcomputing** [comment]
I don't think the MAX232 will work because it is a 5V part. We are powering it with 3.3V so the MAX3232 is the right part.

**Comment by oXL0C0Xo** [comment]
OK, thank you for letting me know!
