### ISSUE TITLE
Mounting Ideas

### ISSUE THREAD

**Issue by skadarnold** [scrapcomputing/ThrottleBlaster#3]
I have been thinking of different ways to conveniently mount and control the ThrottleBlaster and I thought I might share some ideas.

I ordered a few of these PCI brackets with predrilled holes for wifi antenna's
[PCI Brackets](https://www.aliexpress.us/item/3256805155324104.html?spm=a2g0o.order_list.order_list_main.5.49481802lBbWZp&gatewayAdapt=glo2usa
)
In previous projects I have found these wifi antenna holes to be a perfect size for things like 3.5mm audio jacks and bolt mounted buttons. I was thinking it might work well to mount two buttons and a potentiometer so that you had access to control from the back.  

Originally I was thinking it might work well to used the knurled rotary encoder to bolt through one of the antenna holes which would also mount the pcb and pico with it all in one, but I don't think it would work all that well with this current design. Maybe a redesign where the rotary could be at a 90 degree angle and the pico and board were angled in a way to be flush with the pci slot could be a good option though.

**Comment by scrapcomputing** [comment]
Thanks for sharing your ideas. Good to know that these wifi card brackets have such conveniently sized hole! 

Yeah, I think the current board is a bit too wide. But you can always mount it on the side and use some wires to connect the rotary encoder to the board, like you do on a gotek. I don't think that rotary encoders with 90 degree mounts are widely available.
The header for the potentiometer is on the side, so you might be able to mount it on the PCB.
