### ISSUE TITLE
Rotary Encoder

### ISSUE THREAD

**Issue by oXL0C0Xo** [scrapcomputing/ThrottleBlaster#4]
Hi, I have a question about what type of rotary encoder to use. Sorry for my lack of knowledge about them, but when I look up the part number "EC11E" on mouser, quite a few options come up with different attributes. Do you have a suggested part number that is best for this? Any help would be appreciated. Thanks again!

**Comment by scrapcomputing** [comment]
As far as I know any 5-pin rotary encoder (3-pins for the rotary circuit and 2 for the push-button) with the same footprint should do. There are a lot of variants, the main difference being the type of knob they can accommodate. So you will have to choose one according to the knob you are planning to get.
"Alps EC11E" is the footprint I used for the PCB, but should fit most common rotary encoders of that pinout and size. The ones I used in my build are some very cheap clones I got in a kit, I think 5 or 6 of them along with their knobs. You can easily find such inexpensive kits online.
