### ISSUE TITLE
StpClk 0.1mm wire success

### ISSUE THREAD

**Issue by skadarnold** [scrapcomputing/ThrottleBlaster#9]
I was able to use the throttle blaster using 0.1mm enameled wire at the stpclk pin under the CPU. Originally I was testing with 30 gauge but I feel like that is too tight of a fit and felt weird in socket. The 0.1mm can hardly be noticed when inserting the CPU which is good, but can also be tricky to hold steady. I think maybe a little thicker might be the sweet spot for this. 

https://www.amazon.com/gp/product/B08ZMP5GXD/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
![signal-2024-04-28-141330_002](https://github.com/scrapcomputing/ThrottleBlaster/assets/80274795/b6e82bbe-a733-4ca5-b7ce-65f0aac6d54e)

I used a bit of kapton tape to keep a little slack near the socket.

**Comment by scrapcomputing** [comment]
Awesome, thanks for sharing the photo!
